# Generated by Django 4.1.2 on 2022-10-18 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_notemodel_options_literarynotemodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='literarynotemodel',
            options={'verbose_name': 'Literary Note', 'verbose_name_plural': 'Literary Notes'},
        ),
        migrations.AddField(
            model_name='literarynotemodel',
            name='page',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='literarynotemodel',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
