# Generated by Django 4.0.6 on 2022-09-20 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_notemodel_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notemodel',
            name='title',
            field=models.CharField(blank=True, max_length=2000, null=True, unique=True),
        ),
    ]
