# Generated by Django 4.1.2 on 2022-10-24 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_alter_literarynotemodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notemodel',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='notes/audio/'),
        ),
    ]
