# Generated by Django 4.1.5 on 2023-02-09 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_rename_page_literarynotemodel_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notemodel',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notes.notemodel'),
        ),
    ]
