site_name: Writing The Tabula Rasa
site_url: https://sebastianrvaldivia.github.io/WritingTheTabulaRasa/

docs_dir: "./docs"

theme: 
  name: material
  logo: _siteassets/logo.svg
  favicon: _siteassets/logo.svg
  palette:
    primary: black

nav:
  - Home: home/index.md
  - Book: 
    - English: book/english/index.md
    - Español: book/español/index.md
  - Code Documentation: 
    - Index: software-documentation/index.md
    - Back End: software-documentation/backend/index.md
    - Client: software-documentation/client/index.md
    - Lite Client: software-documentation/lite/index.md
    - Documentation for design and behavior: software-documentation/design/index.md

repo_url: https://github.com/SebastianRValdivia/WritingTheTabulaRasa
repo_name: Writing The Tabula Rasa

plugins:
  - search

