# Generated by Django 4.1.4 on 2023-01-08 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('metadata', '0002_categorymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizzModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=2000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='metadata.categorymodel')),
            ],
            options={
                'verbose_name': 'Quizz',
                'verbose_name_plural': 'Quizzes',
            },
        ),
        migrations.CreateModel(
            name='QuizzQuestionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(choices=[(0, 'Formulation'), (1, 'Choice'), (2, 'Join'), (3, 'List')], default=0)),
                ('question', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('quizz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quizzes.quizzmodel')),
            ],
            options={
                'verbose_name': 'Quizz question',
                'verbose_name_plural': 'Quizz questions',
            },
        ),
        migrations.CreateModel(
            name='QuizzListItemQuestionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('content', models.CharField(max_length=2000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.quizzquestionmodel')),
            ],
            options={
                'verbose_name': 'Quizz list item question',
                'verbose_name_plural': 'Quizz list item questions',
            },
        ),
        migrations.CreateModel(
            name='QuizzJoinElementQuestionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=2000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.quizzquestionmodel')),
                ('related', models.ManyToManyField(blank=True, to='quizzes.quizzjoinelementquestionmodel')),
            ],
            options={
                'verbose_name': 'Quizz join question element',
                'verbose_name_plural': 'Quizz join element questions element',
            },
        ),
        migrations.CreateModel(
            name='QuizzFormulationQuestionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('response', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('quizz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quizzes.quizzquestionmodel')),
            ],
            options={
                'verbose_name': 'Quizz formulation question',
                'verbose_name_plural': 'Quizz formulation questions',
            },
        ),
        migrations.CreateModel(
            name='QuizzChoiceQuestionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=2000)),
                ('correct', models.BooleanField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.quizzquestionmodel')),
            ],
            options={
                'verbose_name': 'Question quizz choice',
                'verbose_name_plural': 'Question quizz choices',
            },
        ),
    ]
