# Generated by Django 4.1.4 on 2023-01-08 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizzformulationquestionmodel',
            name='question',
        ),
    ]
