# Generated by Django 4.1.4 on 2023-01-08 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_remove_quizzformulationquestionmodel_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizzformulationquestionmodel',
            name='quizz',
        ),
        migrations.AddField(
            model_name='quizzformulationquestionmodel',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quizzes.quizzquestionmodel'),
            preserve_default=False,
        ),
    ]
