# Generated by Django 4.1.4 on 2023-01-03 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_alter_quizzmodel_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizzquestionmodel',
            name='content',
        ),
        migrations.AddField(
            model_name='quizzquestionmodel',
            name='question',
            field=models.TextField(default='question'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizzquestionmodel',
            name='response',
            field=models.TextField(default='response'),
            preserve_default=False,
        ),
    ]
