# Generated by Django 4.1.4 on 2023-01-03 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_remove_quizzquestionmodel_content_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuizzQuestionModel',
            new_name='QuizzFormulationQuestionModel',
        ),
    ]
