# Generated by Django 4.1.4 on 2023-01-08 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_remove_quizzformulationquestionmodel_quizz_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizzquestionmodel',
            old_name='size',
            new_name='type',
        ),
    ]
