# Generated by Django 4.1.4 on 2023-01-03 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0005_quizzchoicemodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizzchoicemodel',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quizzes.quizzchoicesquestionmodel'),
            preserve_default=False,
        ),
    ]
