# Generated by Django 4.1.5 on 2023-02-20 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0005_flashcardcollection_flashcardmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FlashCardCollection',
            new_name='FlashCardCollectionModel',
        ),
    ]
