# Generated by Django 4.1.7 on 2023-03-29 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0006_rename_flashcardcollection_flashcardcollectionmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcardcollectionmodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
