# Generated by Django 4.1.4 on 2023-01-07 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0006_quizzchoicemodel_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizzOrderListQuestionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('quizz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quizzes.quizzmodel')),
            ],
            options={
                'verbose_name': 'Quizz order list question',
                'verbose_name_plural': 'Quizz order list questions',
            },
        ),
        migrations.CreateModel(
            name='QuizzListItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('content', models.CharField(max_length=2000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.quizzorderlistquestionmodel')),
            ],
            options={
                'verbose_name': 'Quizz list item question',
                'verbose_name_plural': 'Quizz list item questions',
            },
        ),
        migrations.CreateModel(
            name='QuizzJoinQuestionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('quizz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quizzes.quizzmodel')),
            ],
            options={
                'verbose_name': 'Quizz join question',
                'verbose_name_plural': 'Quizz join questions',
            },
        ),
        migrations.CreateModel(
            name='QuizzJoinElementModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=2000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.quizzjoinquestionmodel')),
                ('related', models.ManyToManyField(to='quizzes.quizzjoinelementmodel')),
            ],
            options={
                'verbose_name': 'Quizz join question element',
                'verbose_name_plural': 'Quizz join element questions element',
            },
        ),
    ]
