# Generated by Django 4.1.4 on 2023-01-07 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0007_quizzorderlistquestionmodel_quizzlistitemmodel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizzjoinelementmodel',
            name='related',
        ),
    ]
