# Generated by Django 4.1.4 on 2023-01-07 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0008_remove_quizzjoinelementmodel_related'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizzjoinelementmodel',
            name='related',
            field=models.ManyToManyField(to='quizzes.quizzjoinelementmodel'),
        ),
    ]
