# Generated by Django 4.2.1 on 2023-05-08 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0008_flashcardtestresultmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizzquestionmodel',
            name='quizz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quizzes.quizzmodel'),
        ),
    ]
