# Generated by Django 4.1.4 on 2023-01-07 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0009_quizzjoinelementmodel_related'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizzjoinelementmodel',
            name='related',
            field=models.ManyToManyField(blank=True, to='quizzes.quizzjoinelementmodel'),
        ),
    ]
