# Generated by Django 4.1.4 on 2023-01-06 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goalmodel',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='goalmodel',
            old_name='updated_at',
            new_name='updated',
        ),
    ]
