# Generated by Django 4.0.6 on 2022-09-29 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goalmodel',
            old_name='finish_time',
            new_name='finish',
        ),
    ]
