# Generated by Django 4.1.2 on 2022-10-14 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_rename_finish_time_goalmodel_finish'),
    ]

    operations = [
        migrations.RenameField(
            model_name='objectivemodel',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='objectivemodel',
            old_name='updated_at',
            new_name='updated',
        ),
    ]
