# Generated by Django 4.1.2 on 2022-10-28 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheatsheets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheatmodel',
            name='size',
            field=models.IntegerField(choices=[(0, 'Auto'), (1, 'Simple'), (2, 'Double'), (3, 'Full')], default=0),
        ),
    ]
