# Generated by Django 4.1.3 on 2022-12-09 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheatsheets', '0002_cheatmodel_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheetmodel',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
