# Generated by Django 4.2.1 on 2023-05-20 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheatsheets', '0005_sheetmodel_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheetmodel',
            name='color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
