# Generated by Django 4.1.2 on 2022-10-29 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0002_encyclopediapagemodel_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncyclopediaCardModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='encyclopedia.encyclopediapagemodel')),
            ],
            options={
                'verbose_name': 'Encyclopedia Card',
                'verbose_name_plural': 'Encyclopedia Cards',
            },
        ),
    ]
