# Generated by Django 4.1.4 on 2022-12-15 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0004_encyclopediapagemodel_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='encyclopediacardmodel',
            old_name='page',
            new_name='pg',
        ),
    ]
