# Generated by Django 4.2.1 on 2023-05-16 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('encyclopedia', '0006_encyclopediapagemodel_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncyclopediaDiscussionPostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encyclopedia.encyclopediapagemodel')),
            ],
            options={
                'verbose_name': 'Encyclopedia discussion post',
                'verbose_name_plural': 'Encyclopedia discussion posts',
            },
        ),
    ]
