# Generated by Django 4.1.2 on 2022-10-14 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskmodel',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='taskmodel',
            old_name='updated_at',
            new_name='updated',
        ),
    ]
