# Generated by Django 4.1.7 on 2023-04-10 00:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0002_alter_practicecompletionmodel_routine_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeExerciseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=2000)),
                ('content', models.TextField()),
                ('difficulty', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(5)])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Practice exercise',
                'verbose_name_plural': 'Practice exercises',
            },
        ),
        migrations.AlterModelOptions(
            name='practicecompletionmodel',
            options={'verbose_name': 'Practice completion', 'verbose_name_plural': 'Practice completions'},
        ),
        migrations.AlterModelOptions(
            name='practiceroutinemodel',
            options={'verbose_name': 'Practice routine', 'verbose_name_plural': 'Practice routines'},
        ),
        migrations.AlterModelOptions(
            name='userassignedpracticeroutinemodel',
            options={'verbose_name': 'User routine', 'verbose_name_plural': 'User routines'},
        ),
    ]
