# Generated by Django 4.1.7 on 2023-04-17 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0004_practiceexercisemodel_routine'),
    ]

    operations = [
        migrations.AddField(
            model_name='practiceroutinemodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
