# Generated by Django 4.1.7 on 2023-04-19 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0005_practiceroutinemodel_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='userassignedpracticeroutinemodel',
            name='scheduled',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
