# Generated by Django 4.1.7 on 2023-04-24 19:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedules', '0002_userschdulemodel_day'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserSchduleModel',
            new_name='UserHourModel',
        ),
        migrations.AlterModelOptions(
            name='userhourmodel',
            options={'verbose_name': 'Hour', 'verbose_name_plural': 'Hours'},
        ),
    ]
