# Generated by Django 4.1.7 on 2023-04-27 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0003_rename_userschdulemodel_userhourmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertimetablemodel',
            name='title',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
