# Generated by Django 4.1.7 on 2023-04-27 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0004_usertimetablemodel_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertimetablemodel',
            name='title',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
