# Generated by Django 4.2.8 on 2023-12-20 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lecturemodel',
            options={'verbose_name': 'Lecture', 'verbose_name_plural': 'Lectures'},
        ),
        migrations.AddField(
            model_name='lecturemodel',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='lectures_videos/thumbnails/'),
        ),
    ]
