# Generated by Django 4.0.6 on 2022-10-06 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ResourceModel',
            new_name='ReferenceModel',
        ),
        migrations.AlterModelOptions(
            name='referencemodel',
            options={'verbose_name': 'Reference', 'verbose_name_plural': 'References'},
        ),
    ]
