# Generated by Django 4.1.3 on 2022-12-05 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_imagemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagemodel',
            name='title',
        ),
    ]
