# Generated by Django 4.1.5 on 2023-01-17 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_remove_imagemodel_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningResourceReferenceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=2000)),
                ('autor', models.CharField(blank=True, max_length=2000, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Learning resource reference',
                'verbose_name_plural': 'Learning resource references',
            },
        ),
    ]
