# Generated by Django 4.1.5 on 2023-01-17 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resources', '0004_learningresourcereferencemodel'),
        ('notes', '0005_alter_literarynotemodel_reference'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReferenceModel',
        ),
        migrations.AddField(
            model_name='learningresourcereferencemodel',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
