# Generated by Django 4.1.7 on 2023-04-25 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resources', '0006_rename_learningresourcereferencemodel_learningresourcemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAssignedLearningResourceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('resource', models.ManyToManyField(to='resources.learningresourcemodel')),
            ],
        ),
    ]
