# Generated by Django 4.1.7 on 2023-04-25 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0007_userassignedlearningresourcemodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userassignedlearningresourcemodel',
            options={'verbose_name': 'User assigned learning resource', 'verbose_name_plural': 'User assigned learning resources'},
        ),
        migrations.RenameField(
            model_name='userassignedlearningresourcemodel',
            old_name='resource',
            new_name='resources',
        ),
        migrations.RemoveField(
            model_name='learningresourcemodel',
            name='owner',
        ),
    ]
