# Generated by Django 4.1.7 on 2023-04-25 20:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0008_alter_userassignedlearningresourcemodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningresourcemodel',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='learningresourcemodel',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userassignedlearningresourcemodel',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userassignedlearningresourcemodel',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
