# Generated by Django 4.2.1 on 2023-05-08 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0010_learningresourcemodel_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningresourcemodel',
            name='autor',
        ),
    ]
