# Generated by Django 4.2.1 on 2023-06-07 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0009_alter_encyclopediapagemodel_image'),
        ('resources', '0011_remove_learningresourcemodel_autor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageModel',
        ),
    ]
