# Generated by Django 4.1.4 on 2022-12-17 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stepmodel',
            name='guide',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='guides.guidemodel'),
            preserve_default=False,
        ),
    ]
