# Generated by Django 4.1.4 on 2022-12-20 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0002_stepmodel_guide'),
    ]

    operations = [
        migrations.AddField(
            model_name='stepmodel',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
