# Generated by Django 4.1.4 on 2022-12-30 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0002_categorymodel'),
        ('research', '0002_alter_researchprocessmodel_conclusion'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchprocessmodel',
            name='metadata',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='metadata.metadatamodel'),
        ),
    ]
