name: Functional Tests CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]
        node-version: [16.x]

    services:
      selenium:
        image: selenium/standalone-firefox

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: ./client

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install quasar
      run: npm i -g @quasar/cli

    - name: Install server dependencies
      working-directory: ./server
      run: |
        python3 -m pip install --upgrade pip
        pip3 install -r requirements.txt

    - name: Run dev_build
      working-directory: ./
      run: ./dev_build.sh

    - name: Run tests
      working-directory: ./server
      run: python3 functional_tests.py
