name: Lite functional tests CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]
    services:
      selenium:
        image: selenium/standalone-firefox
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install
    - name: Install Dependencies
      working-directory: ./server
      run: |
        python3 -m pip install --upgrade pip
        pip3 install -r requirements.txt
    - name: Run server
      working-directory: ./server
      run: python3 manage.py runserver &
    - name: Run tests
      working-directory: ./server
      run: python3 lite_functional_tests.py
